# Generated by Django 4.0.1 on 2022-12-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atchviements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('date_place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('date_place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hackthons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('sub_topic', models.CharField(max_length=50)),
                ('date_place', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=500)),
                ('date_place', models.CharField(max_length=500)),
                ('paragraph', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField()),
                ('persentage', models.IntegerField()),
            ],
        ),
    ]
