# Generated by Django 4.0.1 on 2022-12-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_resume_alter_skill_id_alter_skill_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='last_date',
            field=models.CharField(default=['datetime', 'timezone'], max_length=50),
            preserve_default=False,
        ),
    ]
