# Generated by Django 4.0.1 on 2022-12-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roles_alter_certificate_id_alter_hackthons_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='company',
        ),
    ]
