# Generated by Django 4.0.1 on 2022-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_roles_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='company',
            field=models.CharField(default=['datetime', 'timezone'], max_length=50),
            preserve_default=False,
        ),
    ]
